### 全件取得
GET http://localhost:8080/api/categoryinfo/init

### ID指定取得 (ID: 3)
GET http://localhost:8080/category-info/3

### 名前指定取得 (categoryName: "バッテリー")
GET http://localhost:8080/category-info/name/バッテリー

### 新規登録
POST http://localhost:8080/category-info
Content-Type: application/json

{
    "categoryName": "付属品",
    "deleteFlag": "0",
    "createDate": "2024-11-11T00:00:00",
    "updateDate": "2024-11-11T00:00:00"
}

### カテゴリー全件取得
GET http://localhost:8080/api/categoryinfo/init

### 在庫一覧から全件検索
GET http://localhost:8080/api/stockinfo/init

### 在庫一覧からcategoryId指定検索
GET http://localhost:8080/api/stockinfo/category?categoryId=1

http://localhost:8080/api/stockinfo/search?categoryId=1&name=undefined
